### ISSUE TITLE
The filesystem is not available

### ISSUE THREAD

**Issue by h4yd3n-ng** [1j01/98#21]
Get an error when running on my computer saying The filesystem is not available, it failed to initalize.

**Comment by 1j01** [comment]
You need an HTTP server; it won't work opening `index.html` directly in your browser.
I recommend [live-server](https://www.npmjs.com/package/live-server) for development, as it will automatically reload on changes.

I see I'm lacking a Development Setup section on the readme. I'll add that soon.
Also I could detect if running from `file:` protocol and show a message; I might do that.

**Comment by 1j01** [comment]
I've added a development setup section: https://github.com/1j01/98#development-setup
Let me know if you need any more help, or if the error persists.
