### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by EliazBobadilla** [1j01/98#38]
![image](https://user-images.githubusercontent.com/71897736/105209807-43d04f00-5b18-11eb-8257-09ea11db8935.png)

**Comment by 1j01** [comment]
This is intended behavior :)

**Comment by 1j01** [comment]
![image](https://user-images.githubusercontent.com/3630663/105621752-0f3eea80-5dd9-11eb-9f97-ca18fa5f317f.png)

**Comment by UltiRequiem** [comment]
Nice
