### ISSUE TITLE
make_http_index file not found, clears filesystem-index.json

### ISSUE THREAD

**Issue by ishaan-sangwan** [1j01/98#91]
when running npm start 
make-fs-index command in package.json is run 
```js
"make-fs-index": "make_http_index | json > filesystem-index.json"
```
but there is not make_http_index shell file thus return nothing which deletes the content in filesystem-index.json making the file system crash
![image](https://github.com/1j01/98/assets/69313039/3828bca7-6d55-40a9-b4d9-b51386146417)

**Comment by 1j01** [comment]
This script currently assumes `browserfs@2.0.0` is installed globally. `npm i -g browserfs@2.0.0`

I noted this here, but it's not very discoverable as a note:
https://github.com/1j01/98/blob/361bd759a6d9b71d0fad9e479840598dc0128bb6/package.json#L55-L58

I'm sure this situation will be improved when overhauling the filesystem, needed to fix other problems with it.
